Vagrant.configure("2") do |config|
  $masterIp = "192.168.60.210"
  $www01Ip = "192.168.60.211"

  # master vm
  config.vm.define :master do |master|
      master.vm.box = "dbsq64"
      master.vm.box_url = "http://www.emken.biz/vagrant-boxes/debsqueeze64.box"
      master.vm.hostname = "noc.olindata.com"
      master.vm.network :private_network, :ip => $masterIp

      master.vm.provision :shell, :path => "puppetmaster.sh"

      master.vm.synced_folder "../modules", "/etc/puppet/modules", type: "nfs"
      master.vm.synced_folder "../manifests", "/etc/puppet/manifests", type: "nfs"
      master.vm.synced_folder "../hieradata", "/etc/puppet/hieradata", type: "nfs"

  end

  # www01 vm
  config.vm.define :www01 do |www01|
      www01.vm.box = "dbsq64"
      www01.vm.box_url = "http://www.emken.biz/vagrant-boxes/debsqueeze64.box"
      www01.vm.hostname = "www01.olindata.com"
      www01.vm.network :private_network, :ip => $www01Ip

      www01.vm.provision :shell, :path => "puppetagent.sh", :args => "#{$masterIp}"
  end
end
